fix: resolve issue with ordering of middleware being applied
mikro-orm/nestjs pull request #189
Opened 2024-09-18 13:02 UTC by tsangste

When setting up the nestjs modules with MikroORM there is a chance it can throw `Using global EntityManager instance methods for context specific actions is disallowed.` when interacting with the EM within another middleware.  

This fix applies to both single and multi database set-ups.

2024-09-21 14:24 UTC, tsangste commented
> i cant say i like the naming, the word `multiple` feels weird here, also the whole point of that module is to deal with the middleware, why should we rename it in the first place?

The module doesn't just handle the middleware it also handles registering multiple `MikroOrm` to allow use of the `MikroOrms` token for DI, which is why I thought it would be better to rename it to `multiple`.

2024-09-21 15:08 UTC, B4nan commented
the user still needs to do the `MikroOrmModule.forRoot` calls explicitly, right? sounds like an implementation detail to me, from user point of view, it doesn't do anything else than the middleware i would say.

strictly speaking, the renaming of various symbols and types is a breaking change, i would rather keep the old naming everywhere

2024-09-21 17:58 UTC, tsangste commented
> the user still needs to do the `MikroOrmModule.forRoot` calls explicitly, right? sounds like an implementation detail to me, from user point of view, it doesn't do anything else than the middleware i would say.
> 
> strictly speaking, the renaming of various symbols and types is a breaking change, i would rather keep the old naming everywhere

Yes the user would be required to `MikroOrmModule.forRoot` but that would always be the case for each database. But going along with the export changes to expose the `MikroOrms` (https://github.com/mikro-orm/nestjs/pull/88) and that this specific middleware is only used for multiple database it makes sense for the module to be named more scope to used for mutiple database.  Also I thought there would might be a case where someone could want to use the `MikroOrms` token to get all databases but might not require the middleware (was planning to do after as it did make sense as part of this PR to disable the middleware) and use the DI scopes. 

Yeah I understand adding the new `MULTPLE_MIKRO_ORM_MODULE_OPTIONS` symbol is a breaking change but I wanted those options to be closer to the module due to the renaming and it being scoped to multiple databases, but as this should be used internally I didn't think this would be an issue.  Either way I am happy to continue using the old symbol.

2024-11-09 20:36 UTC, tsangste commented
@B4nan, I have added additional tests and a test to show the issue arising; I have also found that this issue also occurs with the original middleware registration within `mikro-orm-core.module` and I think the fix is to move the middleware registration up to `mikro-orm.module` but I think I would do this in another PR

2024-11-10 09:53 UTC, B4nan requested changes
few notes to begin with, the main takeaway: lets rename all the symbols from `Multiple*` to just `Multi*`, feels like better english to me

also be careful with all the renames, there are still breaking changes in this PR

2024-11-10 09:53 UTC, B4nan commented on README.md
> +    MultipleMikroOrmModule.forRoot()
i know i am repeating myself, but this feels like a really weird language construct. lets at least call it `multi` instead of `multiple`

```suggestion
    MultiMikroOrmModule.forRoot(),
```

2024-11-10 09:53 UTC, B4nan commented on README.md
> +You can define multiple database connections by registering several MikroOrmModules, each with a unique contextName and setting registerRequestContext to false. If you want to use the middleware requ
```suggestion
You can define multiple database connections by registering multiple `MikroOrmModule`s, each with a unique `contextName`. You will need to disable the automatic request context middleware by setting `registerRequestContext` to `false`, as it wouldn't work with this approach - note that this needs to be part of all your `MikroOrmModule`s with non-default `contextName`. To have the same automatic request context behaviour, you must register `MultiMikroOrmModule` with `forRoot()` instead:
```

i don't even know what that part about "or use NestJS `Injection Scope`" was supposed to mean, lets just remove that. if you want to have that there, let's come up with something understandable, accompanied by examples. also fixed the english a bit, not a native speaker myself, so i hope i actually made it better 🙃

2024-11-10 09:53 UTC, B4nan commented on src/mikro-orm.module.ts
> +  // Remove this in the next major version, kept for backwards compatibility
this needs to be proper jsdoc with `@deprecated` tag

2024-11-10 09:53 UTC, B4nan commented on src/mikro-orm.module.ts
>      };
also i wonder if this proposed rename/BC is actually needed, will things be any different if people keep using the `forMiddleware` after those changes?

2024-11-10 09:53 UTC, B4nan commented on src/typings.ts
> +export type MultipleMikroOrmModuleOptions = {
renaming any publicly exported symbol is a breaking change

2024-11-10 09:53 UTC, B4nan commented on tests/mikro-orm.middleware.test.ts
>    });
lets not remove existing tests, now you only test some fail state, but there are no tests for the happy path

2024-11-10 20:11 UTC, tsangste commented on README.md
> +    MultipleMikroOrmModule.forRoot()
Yeah I can switch it to `Multi`, but originally I followed the naming from the middleware `multiple-mikro-orm.middleware.ts` to keep consistency. If you are happy to have them different I will change.

2024-11-10 20:14 UTC, tsangste commented on src/mikro-orm.module.ts
>      };
The original reason why I wanted to switch to `forRoot` was that this follows the nestjs naming convention that this should only be registered once and to correct the original naming mistake when I first did this.

2024-11-10 20:14 UTC, B4nan commented on README.md
> +    MultipleMikroOrmModule.forRoot()
filenames are not relevant, users dont see them at all unless they browse the package code, i am fine with renaming them

2024-11-10 20:15 UTC, tsangste commented on tests/mikro-orm.middleware.test.ts
>    });
I will revert to the previous tests, I did this originally to show the issue that is caused and while trying to get both working there is a timing issue when tearing down and running the next tests it was failing.

2024-11-10 20:23 UTC, B4nan commented on src/mikro-orm.module.ts
>      };
So it has no effect, just a rename. Well, to me what we have now is actually better, why should we make users import two different symbols instead of one?

2024-11-10 20:23 UTC, tsangste commented on README.md
> +    MultipleMikroOrmModule.forRoot()
The middlware class is called `MultipleMikroOrmMiddleware` so happy with keep this inconsistency?

2024-11-10 20:30 UTC, B4nan commented on README.md
> +    MultipleMikroOrmModule.forRoot()
well, that's an implementation detail, users don't come across that name really, right? they are supposed to use `MikroOrmModule.forMiddleware()`

all in all, I would keep the old names everywhere as said in the other comment, since this is not really fixing anything. we can rename things in v7.

2024-11-10 20:32 UTC, tsangste commented on README.md
> +    MultipleMikroOrmModule.forRoot()
sounds good to me 👍

2024-11-10 20:44 UTC, tsangste commented on src/mikro-orm.module.ts
>      };
Sorry I think I am a bit confused, are you asking:

1. We should keep this and continue to use `MikroOrmModule.forMiddleware()`
2. Rename the `forRoot` to `forMiddleware` for `MultiMikroOrmModule`?

if it is point 1 it is not possible as this is the issue I am trying to fix due to the middleware being registered in a nested module it will be registered later that we want. We want people to stop using it this way and use the new way.

if it is point 2 I would prefer we stick to the nestjs naming conventions.

2024-11-10 20:49 UTC, B4nan commented on src/mikro-orm.module.ts
>      };
I would like to keep `MikroOrmModule.forMiddleware()`, I dont follow why it should not be possible, since your current changes did it that way, or not? Its just a static name, I am asking you to keep this user facing API the same, I don't care much about what that static method is doing.

2024-11-10 21:00 UTC, tsangste commented on src/mikro-orm.module.ts
>      };
Yeah it isn't possible hence the reason of using `MultiMikroOrmModule.forRoot()` due to the way that nestjs registers the middleware e.g.

Using the example

Given:

    MikroOrmModule
        MultiMikroOrmModule
            MultipleMikroOrmMiddleware 
    FeatureModule
        FeatureMiddleware

Resolution:

    FeatureMiddleware
    MultipleMikroOrmMiddleware 

This is due to `FeatureMiddleware` being closer to the root module than `MultipleMikroOrmMiddleware`

and with my new changes it will be: 

Given:

    MikroOrmModule
    MultiMikroOrmModule
        MultipleMikroOrmMiddleware 
    FeatureModule
        FeatureMiddleware

Resolution:

    MultipleMikroOrmMiddleware 
    FeatureMiddleware

based on information from nestjs issue (https://github.com/nestjs/nest/pull/11133) and we have to hack our own way to get the middleware to register in the correct order

This is also an issue with the auto middleware register for a single db but I will do this in another PR

2024-11-17 20:57 UTC, tsangste commented on src/mikro-orm.module.ts
>      };
I don't think you understand how NestJS DI works, the method is static but it still returns a object which defines the module hierarchy 

```typescript
static forMiddleware(options?: MikroOrmMiddlewareModuleOptions): DynamicModule {
    return {
      module: MikroOrmModule,  // this module
      imports: [MultipleMikroOrmModule.forRoot(options)], // the child module
    };
  }
```

because `MultipleMikroOrmModule` is being imported it will be a child module and the middleware will be registered later as I mentioned above.

Again highlighting what I am trying to do is go from the following module imports:

```typescript
@Module({
  imports: [
    MikroOrmModule.forRootAsync({
      contextName: 'database-multi-foo',
      useFactory: () => ({
        registerRequestContext: false,
        ...testOptions,
      }),
    }),
    MikroOrmModule.forRoot({
      contextName: 'database-multi-bar',
      registerRequestContext: false,
      ...testOptions,
    }),
    MikroOrmModule.forMiddleware(), // will cause `MultipleMikroOrmMiddleware.forRoot()` to be a child module and middleware to registered after modules below
    FooModule,
    BarModule,
  ],
})
class AppModule {}
```
to 
```typescript
@Module({
  imports: [
    MikroOrmModule.forRootAsync({
      contextName: 'database-multi-foo',
      useFactory: () => ({
        registerRequestContext: false,
        ...testOptions,
      }),
    }),
    MikroOrmModule.forRoot({
      contextName: 'database-multi-bar',
      registerRequestContext: false,
      ...testOptions,
    }),
    MultipleMikroOrmMiddleware.forRoot(), // Registered in this level and middleware will register before the modules below.
    FooModule,
    BarModule,
  ],
})
class AppModule {}
```
We want to deprecate the old function and use the new way to register.  The old function would still work as long as any module registered after that use middleware are registered as child modules but would make it an extra hoop to work around this.

2024-11-18 06:36 UTC, B4nan commented on src/mikro-orm.module.ts
>      };
> We want to deprecate the old function 

Well, to begin with, you want to, I don't 🙃 I already said I like the current naming more than what you proposed and I don't see a reason to change it.

And I am still convinced you are not correct here, all I am saying is that we can keep the same method name. As you said yourself, it's about what the method returns, and that can be whatever it needs to be. I care about public API, not about this implementation detail. 

> The old function would still work 

This only confirms what I want is possible.

---

So let me try one more time. In your example, you have `MultiMikroOrmModule.forRoot()` which you say would fix something. All I want is you to add this

```ts
class MikroOrmModule {

  static forMiddleware() {
    return MultiMikroOrmModule.forRoot();
  }

}
```

This cannot have any runtime effect on nest DI or anything else, all this does is to add one more line to the call stack.

2024-11-18 09:50 UTC, tsangste commented on src/mikro-orm.module.ts
>      };
I understand the changes now, thanks 👍.  A bit of feedback for next time is to lead with the code example as that helped a lot with what you meant. 

I guess a couple of follow up questions:

- Do you want me to apply the same change to `forRoot` and `forRootAsync` due to the same issue or in another PR?
- I think adding a new `forMulti` within `MikroOrmModule` as a replacement for `forMiddleware` to be more explicit that this is only for multiple databases?
   - As a follow on if you want to keep `forMiddleware` I guess undo all the deprecation changes?

2025-01-22 09:19 UTC, B4nan commented
looks like your approach is not working with nest 11

2025-01-22 11:40 UTC, tsangste commented
> looks like your approach is not working with nest 11

i will give it ago with nestjs 11

2025-01-22 11:45 UTC, B4nan commented
maybe the problem you were trying to solve is no longer valid with v11?

2025-01-22 11:49 UTC, tsangste commented
> maybe the problem you were trying to solve is no longer valid with v11? that's the first thing I would try to verify

Yeah I notice some module changes and will go through it

2025-01-23 10:52 UTC, tsangste commented
> maybe the problem you were trying to solve is no longer valid with v11? that's the first thing I would try to verify

The issue has been resolved https://github.com/nestjs/nest/releases/tag/v11.0.5.

I think with the change `Global Modules` should execute first now and think we should keep the code fix so it works for nestjs 10.

2025-01-23 20:17 UTC, tsangste commented
@B4nan I have updated the `peerDependency` for nestjs 11 to go from `^11.0.5` so anyone installing shouldn't be using anything lower

2025-01-23 20:26 UTC, B4nan commented
why? because of something that was present for years now, in 10.x versions that are still supported? i would keep the peer deps loose, its up to the user to stay up to date. we can enforce this in v7 where we disallow older nest versions, but now it feels a bit weird, especially since it doesn't affect everyone (as mentioned above, the real-world example app still works just fine without any changes, even with lower versions).

2025-01-23 20:31 UTC, B4nan commented
do i get it right that things without your PR worked fine, and with the changes you did here it broke with v11 before 11.0.5?

2025-01-23 20:39 UTC, tsangste commented
> do i get it right that things without your PR worked fine, and with the changes you did here it broke with v11 before 11.0.5?

My changes were mainly to resolve the issue in 10.x where the middleware registered in a global module it could be executed later and the test I made here we were able to catch an issue in nestjs 11 where it made the issue worse due to a bug where it made the global module middleware execute last hence why we should force to go from `^11.0.5` cause even without my fix it would cause the request context be executed last but happy to keep it loose at `^11.0.0` if you want it to be up to the users responsibility.

2025-01-23 20:44 UTC, tsangste commented
If we get this fix in then for nestjs 10.x we can remove this line https://github.com/mikro-orm/nestjs-realworld-example-app/blame/a61ea041db0d0cf24f32f49b262c5bfecd6a726d/src/app.module.ts#L32 in your example project

2025-01-23 21:20 UTC, B4nan commented
> If we get this fix in then for nestjs 10.x we can remove this line [mikro-orm/nestjs-realworld-example-app@a61ea04/src/app.module.ts#L32 (blame)](https://github.com/mikro-orm/nestjs-realworld-example-app/blame/a61ea041db0d0cf24f32f49b262c5bfecd6a726d/src/app.module.ts#L32) in your example project

Oh, now that's interesting, didn't realize it's about this. Agreed that it makes sense to merge it in. 

Let's keep it I guess, since the bump is not released out, I guess its fine to enforce first usable version.

2025-01-23 21:26 UTC, B4nan approved these changes

2025-01-23 21:26 UTC, merged