Multiple database connections
mikro-orm/nestjs pull request #56
Opened 2022-02-19 23:46 UTC by tsangste

The resolves #20 

Changes:
- Create injection tokens for MikroORM and EntityManager
- Add contextName param for `getRepositoryToken` and `InjectRepository`
- Create new `forMiddleware()` register for `MikroOrmModule` so we can register multiple MikroORM's through injection tokens 

Due to the new `forMiddleware` register we have now lost the ability auto register middleware due to the way we have to manually register multiple database connections. Happy to take suggestions if anyone has a better way we can do this.

2022-02-19 23:59 UTC, B4nan commented
Thanks, will try to take a look during next few days.

Worth saying that I don't think we need any breaking changes to support this. This should all be optional and only a new section in the docs should be added, rest should stay unchanged.

Disabling the automatic request context middleware would be a huge breaking change I am not willing to make, but I really believe we can find a way to keep things as they are and just add the new feature.

2022-02-20 00:05 UTC, tsangste commented
That sounds good I'll have another tackle at it with your feedback

2022-02-20 01:10 UTC, tsangste commented
@B4nan updated code without breaking changes

2022-02-20 01:15 UTC, tsangste commented on README.md
> -## Using `AsyncLocalStorage` for request context
I noticed as of v5 `AsyncLocalStorage` is now default so remove this or would you prefer to state this is no longer required?

2022-02-20 01:27 UTC, B4nan commented on README.md
> -## Using `AsyncLocalStorage` for request context
Let's keep it there with a notice like in [here](https://mikro-orm.io/docs/usage-with-nestjs#using-asynclocalstorage-for-request-context)

But we can remove the note about domain api.

2022-02-20 12:03 UTC, B4nan requested changes
looking good so far, found one nit, also the build fails with some TS errors

2022-02-20 12:05 UTC, tsangste commented
Yeah when making some more changes to the request tokens it broken some stuff but I have resolved them now

2022-02-20 12:54 UTC, B4nan approved these changes
looking good, one final nitpick

2022-02-20 12:54 UTC, B4nan commented on src/mikro-orm-core.module.ts
> +    CONTEXT_NAMES.splice(0,CONTEXT_NAMES.length);
this is supposed to be clearning the array, right? if so:

```suggestion
    CONTEXT_NAMES.length = 0;
```

maybe we could use a `Set` instead of array

2022-02-20 13:29 UTC, merged

2022-02-20 14:26 UTC, B4nan commented on src/mikro-orm.common.ts
> +export const getSqlEntityManagerToken = (name: string) => `${name}_SqlEntityManager`;
doing some refactors and came to this place. do we actually need those? if there will be more EMs, we will pick based on the context name, not on their subtype

will try to remove it, as I believe it shouldn't be needed, one decorator should be enough - users will pick the right subtype on the callsite, there is no inference involved

2022-02-20 15:02 UTC, tsangste commented on src/mikro-orm.common.ts
> +export const getSqlEntityManagerToken = (name: string) => `${name}_SqlEntityManager`;
Yeah I wasn't sure if we needed it or not but it does make sense we can use the single EM Injection Token for all the types