Multiple database connection with autoLoadEntities
mikro-orm/nestjs pull request #62
Opened 2022-02-24 18:50 UTC by tsangste

As a user who does not use `autoLoadEntities` I discovered today multiple database connections currently does not work with it. I have added some extra tests around `autoLoadEntities` and created `MikroOrmEntitiesStorage ` to manage them.

I also updated `forFeature` to work with options and contextName param.

2022-02-24 18:57 UTC, B4nan requested changes
thanks!

2022-02-24 18:57 UTC, B4nan commented on tests/.eslintrc.js
> +    'jasmine': true,
why is this needed?

2022-02-24 18:57 UTC, B4nan commented on tests/mikro-orm.module.test.ts
> +      } catch {}
please use `expect(() => ...).toThrow()` instead

2022-02-24 19:05 UTC, tsangste commented on tests/.eslintrc.js
> +    'jasmine': true,
I was using it for the fail function for the try and catch block but with the switch to `expect(() => ...).toThrow()` I can remove this.

2022-02-25 08:23 UTC, B4nan approved these changes

2022-02-25 08:23 UTC, merged